//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportLife.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbonementOrder
    {
        public int OrderId { get; set; }
        public int PriceId { get; set; }
        public int ClientId { get; set; }
    
        public virtual Price Price { get; set; }
        public virtual User User { get; set; }
    }
}
