//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportLife.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.Shedules = new HashSet<Shedule>();
        }
    
        public int group_id { get; set; }
        public Nullable<int> group_max_members { get; set; }
        public Nullable<int> coach_id { get; set; }
        public Nullable<int> sport_id { get; set; }
    
        public virtual Coach Coach { get; set; }
        public virtual Sport_kinds Sport_kinds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shedule> Shedules { get; set; }
    }
}
