//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportLife.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shedule()
        {
            this.Visiting = new HashSet<Visiting>();
        }
    
        public int ShedulId { get; set; }
        public string SheduleDay { get; set; }
        public System.TimeSpan SheduleTime { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> HallId { get; set; }
    
        public virtual Hall Hall { get; set; }
        public virtual SportGroup SportGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visiting> Visiting { get; set; }
    }
}
