//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportLife.Core.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportLifeEntities : DbContext
    {
        public SportLifeEntities()
            : base("name=SportLifeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonement> Abonement { get; set; }
        public virtual DbSet<AbonementOrder> AbonementOrder { get; set; }
        public virtual DbSet<Adress> Adress { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Coach> Coach { get; set; }
        public virtual DbSet<Hall> Hall { get; set; }
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<Shedule> Shedule { get; set; }
        public virtual DbSet<SportCategory> SportCategory { get; set; }
        public virtual DbSet<SportGroup> SportGroup { get; set; }
        public virtual DbSet<SportKind> SportKind { get; set; }
        public virtual DbSet<Visiting> Visiting { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserClaim> UserClaim { get; set; }
        public virtual DbSet<UserLogin> UserLogin { get; set; }
        public virtual DbSet<FileType> FileType { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<DaysInWeek> DaysInWeek { get; set; }
    }
}
