//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportLife.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sports_in_Abonements
    {
        public int sport_in_abonement_id { get; set; }
        public Nullable<int> abonement_id { get; set; }
        public Nullable<int> sport_id { get; set; }
    
        public virtual Abonement Abonement { get; set; }
        public virtual Sport_kinds Sport_kinds { get; set; }
    }
}
