//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportLife.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sport_categories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sport_categories()
        {
            this.Sport_kinds = new HashSet<Sport_kinds>();
        }
    
        public int sport_category_id { get; set; }
        public string sport_category_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sport_kinds> Sport_kinds { get; set; }
    }
}
