//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportLife.Core.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportLifeEntitiesWork : DbContext
    {
        public SportLifeEntitiesWork()
            : base("name=SportLifeEntitiesWork")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonement> Abonements { get; set; }
        public virtual DbSet<Adress> Adresses { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Coach> Coaches { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Hall> Halls { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<Shedule> Shedules { get; set; }
        public virtual DbSet<Sport_categories> Sport_categories { get; set; }
        public virtual DbSet<Sport_kinds> Sport_kinds { get; set; }
        public virtual DbSet<Sports_in_Abonements> Sports_in_Abonements { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Visiting> Visitings { get; set; }
    }
}
